//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugDataModel
{
    using System;
    
    public partial class proc_TugSum_ByCustomer_Result1
    {
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> LastYearSumBG { get; set; }
        public Nullable<int> LastYearSumMD { get; set; }
        public Nullable<int> LastYearSumSM { get; set; }
        public Nullable<int> LastYearToThisMonthSumBG { get; set; }
        public Nullable<int> LastYearToThisMonthSumMD { get; set; }
        public Nullable<int> LastYearToThisMonthSumSM { get; set; }
        public Nullable<int> ThisYearToThisMonthSumBG { get; set; }
        public Nullable<int> ThisYearToThisMonthSumMD { get; set; }
        public Nullable<int> ThisYearToThisMonthSumSM { get; set; }
        public Nullable<int> LastYearThisMonthSumBG { get; set; }
        public Nullable<int> LastYearThisMonthSumMD { get; set; }
        public Nullable<int> LastYearThisMonthSumSM { get; set; }
        public Nullable<int> ThisYearThisMonthSumBG { get; set; }
        public Nullable<int> ThisYearThisMonthSumMD { get; set; }
        public Nullable<int> ThisYearThisMonthSumSM { get; set; }
    }
}
