//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AmountSum_Service
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerShipID { get; set; }
        public string CustomerShipName { get; set; }
        public Nullable<int> BillingID { get; set; }
        public string BillingCode { get; set; }
        public Nullable<System.DateTime> BillingDateTime { get; set; }
        public Nullable<int> SchedulerID { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> FuelAmount { get; set; }
        public Nullable<double> TotalRebate { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Hours { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public Nullable<int> ServiceNatureID { get; set; }
        public string ServiceWorkDate { get; set; }
        public Nullable<int> BigTugNum { get; set; }
        public Nullable<int> MiddleTugNum { get; set; }
        public Nullable<int> SmallTugNum { get; set; }
        public Nullable<int> TugID { get; set; }
        public string TugName { get; set; }
        public string BillMonth { get; set; }
        public string EasCode { get; set; }
        public int EasDays { get; set; }
        public string CreateDate { get; set; }
        public string PayDate { get; set; }
        public string EASTugCode { get; set; }
    }
}
