//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AmountSum_Billing
    {
        public int ID { get; set; }
        public Nullable<int> TugID { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<int> BillingID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CustomerShipID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> BillingTypeID { get; set; }
        public Nullable<int> TimeTypeID { get; set; }
        public Nullable<double> Expr1 { get; set; }
    }
}
