//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Billing_Special
    {
        public int IDX { get; set; }
        public string CustomerName { get; set; }
        public string BillingCode { get; set; }
        public string Month { get; set; }
        public Nullable<int> ShipName { get; set; }
        public Nullable<double> TotalRebate { get; set; }
        public Nullable<double> Amount { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<int> TugNumber { get; set; }
        public Nullable<double> FeulUnitPrice { get; set; }
        public Nullable<double> ServiceUnitPrice { get; set; }
        public string ServiceDate { get; set; }
        public Nullable<int> ServiceNatureID { get; set; }
        public string ServiceNature { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> TEUS { get; set; }
        public Nullable<int> CustomerID { get; set; }
    }
}
