//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Billing
    {
        public int IDX { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string JobNo { get; set; }
        public Nullable<int> BillingTemplateID { get; set; }
        public string ShipLengthRule { get; set; }
        public string ShipTEUSRule { get; set; }
        public Nullable<int> BillingTypeID { get; set; }
        public string BillingTypeValue { get; set; }
        public string BillingTypeLabel { get; set; }
        public string BillingCode { get; set; }
        public string BillingName { get; set; }
        public Nullable<int> TimeTypeID { get; set; }
        public string TimeTypeValue { get; set; }
        public string TimeTypeLabel { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Remark { get; set; }
        public string Month { get; set; }
        public Nullable<int> TimesNo { get; set; }
        public string Status { get; set; }
        public Nullable<int> Phase { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string CreateDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public string LastUpDate { get; set; }
        public string UserDefinedCol1 { get; set; }
        public string UserDefinedCol2 { get; set; }
        public string UserDefinedCol3 { get; set; }
        public string UserDefinedCol4 { get; set; }
        public Nullable<double> UserDefinedCol5 { get; set; }
        public Nullable<int> UserDefinedCol6 { get; set; }
        public Nullable<int> UserDefinedCol7 { get; set; }
        public Nullable<int> UserDefinedCol8 { get; set; }
        public string UserDefinedCol9 { get; set; }
        public string UserDefinedCol10 { get; set; }
    }
}
