//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Inv_Head_Special_Credit
    {
        public int IDX { get; set; }
        public Nullable<int> BillingID { get; set; }
        public string CreditCode { get; set; }
        public string CreditContent { get; set; }
        public Nullable<double> CreditAmount { get; set; }
        public string Remark { get; set; }
        public string CreateDate { get; set; }
        public string Name1 { get; set; }
        public string Month { get; set; }
        public string UserDefinedCol10 { get; set; }
    }
}
