//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NeedApproveBilling
    {
        public Nullable<int> BillingTypeID { get; set; }
        public string BillingCode { get; set; }
        public string BillingName { get; set; }
        public string Remark { get; set; }
        public string Month { get; set; }
        public string CreateDate { get; set; }
        public string LastUpDate { get; set; }
        public int IDX { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> Phase { get; set; }
        public Nullable<int> FlowUserID { get; set; }
    }
}
