//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NeedApproveOrderBilling
    {
        public Nullable<int> BillingID { get; set; }
        public Nullable<int> Phase { get; set; }
        public Nullable<int> TimesNo { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public int OrderID { get; set; }
        public string OrderCode { get; set; }
        public string OrdDate { get; set; }
        public string WorkDate { get; set; }
        public string WorkTime { get; set; }
        public string EstimatedCompletionTime { get; set; }
        public Nullable<int> ShipID { get; set; }
        public string ShipName { get; set; }
        public string ServiceNatureIDS { get; set; }
        public string ServiceNatureNames { get; set; }
        public Nullable<int> WorkStateID { get; set; }
        public string WorkStateValue { get; set; }
        public string WorkStateLabel { get; set; }
        public Nullable<int> BillingTemplateID { get; set; }
        public Nullable<int> BillingTypeID { get; set; }
        public string BillingTypeValue { get; set; }
        public string BillingTypeLabel { get; set; }
        public string BillingCode { get; set; }
        public string BillingName { get; set; }
        public Nullable<int> TimeTypeID { get; set; }
        public string TimeTypeValue { get; set; }
        public string TimeTypeLabel { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Amount { get; set; }
        public string BillingRemark { get; set; }
        public string Month { get; set; }
        public string Status { get; set; }
        public Nullable<int> BillingOwnerID { get; set; }
        public string BillingCreateDate { get; set; }
        public Nullable<int> BillingUserID { get; set; }
        public string BillingLastUpDate { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> MarkID { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public string Task { get; set; }
        public Nullable<int> FlowUserID { get; set; }
        public string System { get; set; }
    }
}
