//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TugSum
    {
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string ServiceWorkDate { get; set; }
        public Nullable<int> BigTugNum { get; set; }
        public Nullable<int> MiddleTugNum { get; set; }
        public Nullable<int> SmallTugNum { get; set; }
        public int IDX { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string ServiceWorkPlace { get; set; }
        public Nullable<int> ServiceNatureID { get; set; }
    }
}
