//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 創建時間 的本地化字符串。
        /// </summary>
        internal static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶 的本地化字符串。
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶管理 的本地化字符串。
        /// </summary>
        internal static string CustomerManage {
            get {
                return ResourceManager.GetString("CustomerManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string Customer_Address {
            get {
                return ResourceManager.GetString("Customer_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文名稱 的本地化字符串。
        /// </summary>
        internal static string Customer_CnName {
            get {
                return ResourceManager.GetString("Customer_CnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶編號 的本地化字符串。
        /// </summary>
        internal static string Customer_Code {
            get {
                return ResourceManager.GetString("Customer_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 聯繫人 的本地化字符串。
        /// </summary>
        internal static string Customer_ContactPerson {
            get {
                return ResourceManager.GetString("Customer_ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 電郵 的本地化字符串。
        /// </summary>
        internal static string Customer_Email {
            get {
                return ResourceManager.GetString("Customer_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文名稱 的本地化字符串。
        /// </summary>
        internal static string Customer_EnName {
            get {
                return ResourceManager.GetString("Customer_EnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 傳真 的本地化字符串。
        /// </summary>
        internal static string Customer_Fax {
            get {
                return ResourceManager.GetString("Customer_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶ID 的本地化字符串。
        /// </summary>
        internal static string Customer_IDX {
            get {
                return ResourceManager.GetString("Customer_IDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 郵編 的本地化字符串。
        /// </summary>
        internal static string Customer_MailCode {
            get {
                return ResourceManager.GetString("Customer_MailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 簡寫 的本地化字符串。
        /// </summary>
        internal static string Customer_SimpleName {
            get {
                return ResourceManager.GetString("Customer_SimpleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 電話 的本地化字符串。
        /// </summary>
        internal static string Customer_Telephone {
            get {
                return ResourceManager.GetString("Customer_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶類型ID 的本地化字符串。
        /// </summary>
        internal static string Customer_TypeID {
            get {
                return ResourceManager.GetString("Customer_TypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主頁 的本地化字符串。
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 語言 的本地化字符串。
        /// </summary>
        internal static string Lan {
            get {
                return ResourceManager.GetString("Lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新時間 的本地化字符串。
        /// </summary>
        internal static string LastUpDate {
            get {
                return ResourceManager.GetString("LastUpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂單 的本地化字符串。
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大拖輪數量 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_BigTugNum {
            get {
                return ResourceManager.GetString("OrderInfor_BigTugNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂單編號 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_Code {
            get {
                return ResourceManager.GetString("OrderInfor_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 創建時間 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_CreateDate {
            get {
                return ResourceManager.GetString("OrderInfor_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下單人ID 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_CustomerID {
            get {
                return ResourceManager.GetString("OrderInfor_CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下單人名稱 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_CustomerName {
            get {
                return ResourceManager.GetString("OrderInfor_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 預估完成時間 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_EstimatedCompletionTime {
            get {
                return ResourceManager.GetString("OrderInfor_EstimatedCompletionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂單ID 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_IDX {
            get {
                return ResourceManager.GetString("OrderInfor_IDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下單人身份 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_IsGuest {
            get {
                return ResourceManager.GetString("OrderInfor_IsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新時間 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_LastUpDate {
            get {
                return ResourceManager.GetString("OrderInfor_LastUpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 聯繫人電子郵件 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_LinkEmail {
            get {
                return ResourceManager.GetString("OrderInfor_LinkEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 聯繫人名稱 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_LinkMan {
            get {
                return ResourceManager.GetString("OrderInfor_LinkMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 聯繫人電話 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_LinkPhone {
            get {
                return ResourceManager.GetString("OrderInfor_LinkPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中拖輪數量 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_MiddleTugNum {
            get {
                return ResourceManager.GetString("OrderInfor_MiddleTugNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下單時間 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_OrdTime {
            get {
                return ResourceManager.GetString("OrderInfor_OrdTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_OwnerID {
            get {
                return ResourceManager.GetString("OrderInfor_OwnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 備註 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_Remark {
            get {
                return ResourceManager.GetString("OrderInfor_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被拖船ID 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_ShipID {
            get {
                return ResourceManager.GetString("OrderInfor_ShipID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被拖船名稱 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_ShipName {
            get {
                return ResourceManager.GetString("OrderInfor_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小拖輪數量 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_SmallTugNum {
            get {
                return ResourceManager.GetString("OrderInfor_SmallTugNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用戶 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_UserID {
            get {
                return ResourceManager.GetString("OrderInfor_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作地點 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_WorkPlace {
            get {
                return ResourceManager.GetString("OrderInfor_WorkPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作狀態ID 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_WorkStateID {
            get {
                return ResourceManager.GetString("OrderInfor_WorkStateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作狀態 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_WorkStateName {
            get {
                return ResourceManager.GetString("OrderInfor_WorkStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作時間 的本地化字符串。
        /// </summary>
        internal static string OrderInfor_WorkTime {
            get {
                return ResourceManager.GetString("OrderInfor_WorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂單管理 的本地化字符串。
        /// </summary>
        internal static string OrderManage {
            get {
                return ResourceManager.GetString("OrderManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂單調度 的本地化字符串。
        /// </summary>
        internal static string OrderScheduling {
            get {
                return ResourceManager.GetString("OrderScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        internal static string OwnerID {
            get {
                return ResourceManager.GetString("OwnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 備註 的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段1 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol1 {
            get {
                return ResourceManager.GetString("UserDefinedCol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段10 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol10 {
            get {
                return ResourceManager.GetString("UserDefinedCol10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段2 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol2 {
            get {
                return ResourceManager.GetString("UserDefinedCol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段3 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol3 {
            get {
                return ResourceManager.GetString("UserDefinedCol3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段4 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol4 {
            get {
                return ResourceManager.GetString("UserDefinedCol4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段5 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol5 {
            get {
                return ResourceManager.GetString("UserDefinedCol5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段6 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol6 {
            get {
                return ResourceManager.GetString("UserDefinedCol6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段7 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol7 {
            get {
                return ResourceManager.GetString("UserDefinedCol7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段8 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol8 {
            get {
                return ResourceManager.GetString("UserDefinedCol8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段9 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol9 {
            get {
                return ResourceManager.GetString("UserDefinedCol9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用戶 的本地化字符串。
        /// </summary>
        internal static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
    }
}
